### ISSUE TITLE
хмм..

### ISSUE THREAD

**Issue by MrrJake** [scamushka/aavegotchi-grabber#1]
Что он делает:? я видел что он нанимает гочи, но в другом файле открывает другие сайты:?

**Comment by scamushka** [comment]
Файл один, он не открывает другие сайты, просто получает текущие листинги и актуальный газ прайс.

**Comment by MsLolita** [comment]
софт годный я ручаюсь

**Comment by ezdizzy** [comment]
Рестарт поиска после ошибки borrow не реализован, то есть если транза не прошла и выдало error...грустненько :'(

**Comment by scamushka** [comment]
> Рестарт поиска после ошибки borrow не реализован, то есть если транза не прошла и выдало error...грустненько :'(

Готово.
