### ISSUE TITLE
Ошибочка

### ISSUE THREAD

**Issue by waxwezloo** [scamushka/aavegotchi-grabber#2]
Когда проводит транзакцию выдает ошибку 
![изображение](https://user-images.githubusercontent.com/80362249/171016330-c9235b8e-a8d6-44bc-b157-9edfec3815f8.png)
Кто-то сталкивался? Как пофиксить?

[2022-05-30 17:35:39.563] ERROR: failure: processing response error (body="{\"jsonrpc\":\"2.0\",\"id\":48,\"error\":
ode\":-32000,\"message\":\"transaction underpriced\"}}", error={"code":-32000}, requestBody="{\"method\":\"eth_sendR
ansaction\",\"params\":[\"0x02f9014f818903831e8480832dc6c08307a1209486935f11c86623dec8a25696e1c19a8659cbf95d80b8e485
cf00000000000000000000000000000000000000000000000000000000000a43de00000000000000000000000000000000000000000000000000
0000001a6d000000000000000000000000000000000000000000000000016345785d8a0000000000000000000000000000000000000000000000
000000000000001c2000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000
0000000000000000000000005f0000000000000000000000000000000000000000000000000000000000000000c080a08eb42f594147d5f04a3d
8857850c0c22551ed3bf8fc2c081bd75c06343b7a06aa6c0fa3bc6b68ac29008b299e5cb084253b39f41000481a468d0b823c69ddb\"],\"id\"
\"jsonrpc\":\"2.0\"}", requestMethod="POST", url="https://polygon-rpc.com/", code=SERVER_ERROR, version=web/5.6.0)

**Comment by scamushka** [comment]
Варианта 3: либо кто-то купил раньше (мало газа), либо нет GHST, либо нет апрува токена. Скорее всего, первое.

**Comment by Tomhunt123** [comment]
Граббер на повторе 1 раз гоча берёт, или он будет брать раз за разом?

**Comment by Tomhunt123** [comment]
> Варианта 3: либо кто-то купил раньше (мало газа), либо нет GHST, либо нет апрува токена. Скорее всего, первое.

?
