### ISSUE TITLE
Обновления?

### ISSUE THREAD

**Issue by Tomhunt123** [scamushka/aavegotchi-grabber#3]
Проверь граббер.частые ошибки,спасибо.

**Comment by Tomhunt123** [comment]
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

**Comment by scamushka** [comment]
> Проверь граббер.частые ошибки,спасибо.

Скоро проверю.

**Comment by scamushka** [comment]
> npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

Это не ошибка.
